{
 "title": "Monitoring",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Количество уникальных пользователей",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "bank_app_unique_users_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Количество предсказаний модели",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "bank_app_predictions_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Потребление RAM",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_virtual_memory_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Загрузка модели",
   "type": "stat",
   "description": "1 - модель загружена\n2 - модель не загружена",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "bank_app_model_loaded", "legendFormat": "__auto" }
   ]
  }
 ]
}